# Site settings
name: To be or not to be.
email: phr_sdu@163.com
author: Ink Peng
url:  
resume_site: 
github: 
baseurl: ""
description: To be or not to be.
meta_description: This is a test.
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: incCool

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

